pcarta1 = input("Ingrese el palo de la carta1 en mínusculas: (basto, espada, oro, copa) ")
pcarta2 = input("Ingrese el palo de la carta2 en mínusculas: (basto, espada, oro, copa) ")
pcarta3 = input("Ingrese el palo de la carta3 en mínusculas: (basto, espada, oro, copa) ")
vcarta1 = int(input("Ingrese el valor de la carta1: (1a12)"))
vcarta2 = int(input("Ingrese el valor de la carta2: (1a12)"))
vcarta3 = int(input("Ingrese el valor de la carta3: (1a12)"))